// Word (.docx) report builder for the Huiskamerconcerten survey dashboard.
// Produces a single editable document with: cover page, KPI summary,
// NPS distribution, attendance, AI analysis (NL/EN), open answers,
// and raw data table. Pure server-side, runs in Cloudflare Workers.

import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  PageOrientation,
  Header,
  Footer,
  PageNumber,
  ShadingType,
} from 'docx'
import type { ResponseRow } from './db'
import type { AnalysisResult } from './ai'
import type { Survey, SurveyQuestion } from './surveys'

type Lang = 'nl' | 'en'

// ===== Color palette (matches dashboard) =====
const COLORS = {
  teal: '1F8F8F',
  tealDark: '146060',
  ink: '2C2A28',
  inkSoft: '5C5852',
  border: 'D4CDB8',
  cream: 'FBF8F2',
  paper: 'F4EEDF',
  green: '2E7D32',
  orange: 'F4A93C',
  red: 'B73229',
}

// ===== i18n helpers =====
function L(lang: Lang) {
  if (lang === 'en') {
    return {
      coverBadge: 'Pensato.org',
      coverTitle: 'Survey report — Series I',
      coverSub: 'House concerts · Jos van Immerseel & Ayako Ito',
      coverResponses: 'Responses',
      coverNps: 'NPS',
      coverDate: 'Date',
      coverCredit: 'Generated by the Pensato.org survey dashboard',
      kpiTitle: 'Key indicators',
      kpiResponses: 'Responses',
      kpiNps: 'NPS score',
      kpiAtmosphere: 'Atmosphere (Q4)',
      kpiAcoustics: 'Acoustics (Q6)',
      kpiRepertoire: 'Repertoire (Q8)',
      kpiInteraction: 'Interaction (Q10)',
      kpiComms: 'Communication (Q12)',
      kpiContribution: 'Contribution (Q14)',
      scoresTitle: 'Average scores per dimension',
      npsTitle: 'NPS distribution',
      npsScore: 'Score',
      npsCount: 'Count',
      npsCategory: 'Category',
      npsDetractors: 'Detractors',
      npsPassives: 'Passives',
      npsPromoters: 'Promoters',
      attendanceTitle: 'Concert attendance',
      attendanceLabel: '# concerts',
      attendanceCount: 'Visitors',
      aiTitle: 'AI analysis & suggestions for Series II',
      aiMeta: (n: number, date: string, provider: string) => `Based on ${n} responses · generated on ${date}${provider ? ' · ' + provider : ''}`,
      aiSummary: 'Summary',
      aiStrong: 'Strengths',
      aiImprove: 'Areas for improvement',
      aiSuggest: 'Concrete suggestions for Series II',
      aiQuotes: 'Selected quotes',
      aiNoData: 'No AI analysis available yet. Generate one in the dashboard first.',
      openTitle: 'Open answers',
      openNoneFor: (q: string) => `No answers for ${q}.`,
      rawTitle: 'Raw data (anonymous)',
      rawDate: 'Date',
      rawNps: 'NPS',
      rawConcerts: '# concerts',
      rawAtmosphere: 'Atmosphere',
      rawAcoustics: 'Acoustics',
      rawRepertoire: 'Repertoire',
      rawJos: 'Jos',
      rawComms: 'Comm.',
      rawContribution: 'Contrib.',
      rawName: 'Name',
      footer: 'Huiskamerconcerten Reeks I · Pensato.org',
      page: 'Page',
      of: 'of',
      sentimentPositive: 'positive',
      sentimentNeutral: 'neutral',
      sentimentCritical: 'critical',
    }
  }
  return {
    coverBadge: 'Pensato.org',
    coverTitle: 'Surveyrapport — Reeks I',
    coverSub: 'Huiskamerconcerten · Jos van Immerseel & Ayako Ito',
    coverResponses: 'Responses',
    coverNps: 'NPS',
    coverDate: 'Datum',
    coverCredit: 'Gegenereerd door het Pensato.org surveydashboard',
    kpiTitle: 'Kerncijfers',
    kpiResponses: 'Responses',
    kpiNps: 'NPS-score',
    kpiAtmosphere: 'Sfeer (Q4)',
    kpiAcoustics: 'Akoestiek (Q6)',
    kpiRepertoire: 'Repertoire (Q8)',
    kpiInteraction: 'Interactie (Q10)',
    kpiComms: 'Communicatie (Q12)',
    kpiContribution: 'Bijdrage (Q14)',
    scoresTitle: 'Gemiddelde scores per dimensie',
    npsTitle: 'NPS-verdeling',
    npsScore: 'Score',
    npsCount: 'Aantal',
    npsCategory: 'Categorie',
    npsDetractors: 'Detractors',
    npsPassives: 'Passives',
    npsPromoters: 'Promoters',
    attendanceTitle: 'Concertdeelname',
    attendanceLabel: '# concerten',
    attendanceCount: 'Bezoekers',
    aiTitle: 'AI-analyse & suggesties voor Reeks II',
    aiMeta: (n: number, date: string, provider: string) => `Op basis van ${n} responses · gegenereerd op ${date}${provider ? ' · ' + provider : ''}`,
    aiSummary: 'Samenvatting',
    aiStrong: 'Sterke punten',
    aiImprove: 'Verbeterpunten',
    aiSuggest: 'Concrete suggesties voor Reeks II',
    aiQuotes: 'Geselecteerde citaten',
    aiNoData: 'Nog geen AI-analyse beschikbaar. Genereer er eerst een in het dashboard.',
    openTitle: 'Open antwoorden',
    openNoneFor: (q: string) => `Geen antwoorden voor ${q}.`,
    rawTitle: 'Ruwe data (anoniem)',
    rawDate: 'Datum',
    rawNps: 'NPS',
    rawConcerts: '# concerten',
    rawAtmosphere: 'Sfeer',
    rawAcoustics: 'Akoestiek',
    rawRepertoire: 'Repertoire',
    rawJos: 'Jos',
    rawComms: 'Comm.',
    rawContribution: 'Bijdrage',
    rawName: 'Naam',
    footer: 'Huiskamerconcerten Reeks I · Pensato.org',
    page: 'Pagina',
    of: 'van',
    sentimentPositive: 'positief',
    sentimentNeutral: 'neutraal',
    sentimentCritical: 'kritisch',
  }
}

// ===== Helpers =====
const round1 = (v: number) => Math.round(v * 10) / 10

// ── Survey-aware answer helpers (sinds 2026-05) ──
// Identieke logica als in stats.ts / csv.ts / ai.ts — bewust gedupliceerd om
// cross-imports tussen libs te vermijden in edge-runtime.
function parseAnswers(row: ResponseRow): Record<string, unknown> {
  if (!row.answers_json) return {}
  try {
    const o = JSON.parse(row.answers_json)
    return o && typeof o === 'object' && !Array.isArray(o) ? o : {}
  } catch { return {} }
}

function getAnswer(row: ResponseRow, code: string, parsed?: Record<string, unknown>): unknown {
  const a = parsed ?? parseAnswers(row)
  if (Object.prototype.hasOwnProperty.call(a, code)) {
    const v = a[code]
    if (v === null || v === undefined) return undefined
    if (typeof v === 'string' && v.trim() === '') return undefined
    return v
  }
  if (code in row) {
    const v = (row as unknown as Record<string, unknown>)[code]
    if (v === null || v === undefined) return undefined
    if (typeof v === 'string' && v.trim() === '') return undefined
    return v
  }
  return undefined
}

function toNumber(v: unknown): number | null {
  if (v === null || v === undefined || v === '') return null
  if (typeof v === 'number') return Number.isFinite(v) ? v : null
  const n = parseFloat(String(v))
  return Number.isFinite(n) ? n : null
}

/** Bereken gemiddelde voor een code, gebruikmakend van answers_json + fallback. */
function avgFor(rows: ResponseRow[], code: string): { value: number; count: number } {
  const vals: number[] = []
  for (const r of rows) {
    const v = toNumber(getAnswer(r, code))
    if (v != null) vals.push(v)
  }
  if (vals.length === 0) return { value: 0, count: 0 }
  return { value: round1(vals.reduce((a, b) => a + b, 0) / vals.length), count: vals.length }
}

/** Legacy avg() — alleen nog gebruikt door interne fallbacks. */
function avg(rows: ResponseRow[], key: keyof ResponseRow): number {
  const vals = rows.map(r => r[key]).filter(v => typeof v === 'number') as number[]
  if (vals.length === 0) return 0
  return round1(vals.reduce((a, b) => a + b, 0) / vals.length)
}

/**
 * NPS-berekening uit een dynamische vragen-snapshot.
 * Zoekt eerst naar een type=nps vraag; valt anders terug op de legacy q1_nps kolom
 * (zodat oude Reeks-I exports zonder snapshot blijven werken).
 */
function npsBreakdown(rows: ResponseRow[], questions: SurveyQuestion[] = []) {
  const npsQ = questions.find(q => q.type === 'nps')
  let scores: number[] = []
  let min = 0, max = 10
  if (npsQ) {
    min = npsQ.scale_min ?? 0
    max = npsQ.scale_max ?? 10
    for (const r of rows) {
      const v = toNumber(getAnswer(r, npsQ.code))
      if (v != null) scores.push(v)
    }
  } else {
    // Legacy fallback (geen survey-snapshot): gebruik q1_nps kolom
    scores = rows.map(r => (r as any).q1_nps).filter(v => typeof v === 'number') as number[]
  }
  const total = scores.length || 1
  let promoters = 0, passives = 0, detractors = 0
  if (max - min === 10) {
    promoters  = scores.filter(v => v >= 9).length
    passives   = scores.filter(v => v >= 7 && v <= 8).length
    detractors = scores.filter(v => v <= 6).length
  } else {
    const range = max - min
    for (const v of scores) {
      if (v >= min + range * 0.8) promoters++
      else if (v >= min + range * 0.6) passives++
      else detractors++
    }
  }
  const nps = scores.length === 0
    ? 0
    : Math.round(((promoters / scores.length) - (detractors / scores.length)) * 100)
  // Distribution per score min..max (meestal 0..10 = 11 buckets)
  const bucketCount = Math.max(1, max - min + 1)
  const dist: number[] = Array.from(
    { length: bucketCount },
    (_, i) => scores.filter(v => Math.round(v) === min + i).length,
  )
  return { promoters, passives, detractors, nps, dist, total, min, max, code: npsQ?.code ?? 'q1_nps' }
}

/**
 * Verdeling voor één choice-vraag. Behoudt de oorspronkelijke options-volgorde
 * uit de snapshot. Geeft lege array terug als er geen antwoorden zijn.
 */
function choiceBreakdown(
  rows: ResponseRow[],
  q: SurveyQuestion,
): { label: string; count: number }[] {
  const counts: Record<string, number> = {}
  for (const r of rows) {
    const v = getAnswer(r, q.code)
    if (v == null) continue
    const s = String(v)
    counts[s] = (counts[s] || 0) + 1
  }
  const out: { label: string; count: number }[] = []
  const seen = new Set<string>()
  // Eerst in de option-order van de snapshot (als die bestaat)
  for (const opt of q.options_nl ?? []) {
    if (counts[opt]) {
      out.push({ label: opt, count: counts[opt] })
      seen.add(opt)
    }
  }
  // Daarna eventuele onverwachte waardes (legacy / vrije tekst)
  for (const k of Object.keys(counts)) {
    if (!seen.has(k)) out.push({ label: k, count: counts[k] })
  }
  return out
}

function fmtDate(iso: string, lang: Lang): string {
  try {
    const d = new Date(iso)
    return d.toLocaleDateString(lang === 'en' ? 'en-GB' : 'nl-BE', { day: '2-digit', month: 'long', year: 'numeric' })
  } catch { return iso }
}

function fmtDateTime(iso: string, lang: Lang): string {
  try {
    const d = new Date(iso)
    return d.toLocaleString(lang === 'en' ? 'en-GB' : 'nl-BE', {
      day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit',
    })
  } catch { return iso }
}

// ===== Reusable docx primitives =====
const NO_BORDER = {
  top:    { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  left:   { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  right:  { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
}

const LIGHT_BORDER = {
  top:    { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
  left:   { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
  right:  { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
}

function p(text: string, opts: any = {}): Paragraph {
  return new Paragraph({
    spacing: { after: 100, ...(opts.spacing || {}) },
    alignment: opts.alignment,
    heading: opts.heading,
    children: [new TextRun({
      text,
      bold: opts.bold,
      italics: opts.italics,
      color: opts.color,
      size: opts.size, // half-points
      font: opts.font,
    })],
  })
}

function emptyP(): Paragraph {
  return new Paragraph({ children: [new TextRun({ text: '' })] })
}

function bullet(text: string, lang: Lang, italic = false): Paragraph {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text, italics: italic })],
  })
}

function kpiCell(label: string, value: string, suffix = ''): TableCell {
  return new TableCell({
    width: { size: 25, type: WidthType.PERCENTAGE },
    margins: { top: 200, bottom: 200, left: 220, right: 220 },
    shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.cream },
    borders: LIGHT_BORDER,
    children: [
      new Paragraph({
        spacing: { after: 60 },
        children: [new TextRun({ text: label, italics: true, size: 18, color: COLORS.inkSoft })],
      }),
      new Paragraph({
        spacing: { after: 40 },
        children: [
          new TextRun({ text: value, bold: true, size: 36, color: COLORS.tealDark }),
          new TextRun({ text: suffix, size: 18, color: COLORS.inkSoft }),
        ],
      }),
    ],
  })
}

// Horizontal "bar" rendered as a simple unicode block string scaled to the value
function bar(value: number, max: number, width = 30): string {
  if (max <= 0) return ''
  const filled = Math.max(0, Math.round((value / max) * width))
  return '█'.repeat(filled) + '░'.repeat(Math.max(0, width - filled))
}

// ===== Section builders =====

function buildCover(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  survey?: Survey,
): Paragraph[] {
  const n = rows.length
  const { nps } = npsBreakdown(rows)
  const today = new Date().toLocaleDateString(lang === 'en' ? 'en-GB' : 'nl-BE', {
    day: '2-digit', month: 'long', year: 'numeric',
  })
  const badge = survey?.series_name ?? t.coverBadge
  const title = survey ? (lang === 'en' ? survey.title_en : survey.title_nl) : t.coverTitle
  const sub = survey
    ? ((lang === 'en' ? survey.subtitle_en : survey.subtitle_nl) ?? t.coverSub)
    : t.coverSub

  return [
    new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 1800 } }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [new TextRun({ text: badge, italics: true, color: COLORS.tealDark, size: 22 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [new TextRun({ text: title, bold: true, color: COLORS.tealDark, size: 56 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
      children: [new TextRun({ text: sub, italics: true, color: COLORS.inkSoft, size: 26 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: `${n}`, bold: true, size: 40, color: COLORS.ink }),
        new TextRun({ text: '   ·   ', color: COLORS.inkSoft, size: 32 }),
        new TextRun({ text: `${nps}`, bold: true, size: 40, color: COLORS.ink }),
        new TextRun({ text: '   ·   ', color: COLORS.inkSoft, size: 32 }),
        new TextRun({ text: today, bold: true, italics: true, size: 32, color: COLORS.ink }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 1600 },
      children: [
        new TextRun({ text: t.coverResponses, color: COLORS.inkSoft, size: 18 }),
        new TextRun({ text: '            ', size: 18 }),
        new TextRun({ text: t.coverNps, color: COLORS.inkSoft, size: 18 }),
        new TextRun({ text: '                ', size: 18 }),
        new TextRun({ text: t.coverDate, color: COLORS.inkSoft, size: 18 }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
      pageBreakBefore: false,
      children: [new TextRun({ text: t.coverCredit, italics: true, color: COLORS.inkSoft, size: 18 })],
    }),
  ]
}

/**
 * Korte label voor KPI-tegels: probeer eerst de Reeks-I i18n strings, anders
 * truncated label_nl van de vraag. Houdt de output netjes als kolomtitel.
 */
function shortKpiLabel(q: SurveyQuestion, lang: Lang, t: ReturnType<typeof L>): string {
  // Heuristische mapping van bekende codes op de bestaande i18n-strings,
  // zodat Reeks-I rapporten exact dezelfde KPI-labels behouden als vroeger.
  const map: Record<string, string> = {
    q4_sfeer: t.kpiAtmosphere,
    q6_akoestiek: t.kpiAcoustics,
    q8_repertoire: t.kpiRepertoire,
    q10_interactie: t.kpiInteraction,
    q12_communic: t.kpiComms,
    q14_bijdrage: t.kpiContribution,
  }
  if (map[q.code]) return map[q.code]
  // Voor onbekende codes: code + verkort label
  const lbl = (lang === 'en' ? q.label_en : q.label_nl) || q.code
  const short = lbl.length > 32 ? lbl.slice(0, 29) + '…' : lbl
  return `${q.code.toUpperCase()} · ${short}`
}

function buildKpiSection(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  questions: SurveyQuestion[] = [],
): (Paragraph | Table)[] {
  const n = rows.length
  const { nps } = npsBreakdown(rows, questions)

  // Dynamische lijst van scale-vragen — in display_order, alleen die met antwoorden
  // (zodat we geen lege "0 / 5" KPI-kaartjes tonen voor pas-toegevoegde vragen).
  const scaleQs = questions.filter(q => q.type === 'scale')
  const scaleCells = scaleQs.map(q => {
    const { value, count } = avgFor(rows, q.code)
    const max = q.scale_max ?? 5
    if (count === 0) {
      return kpiCell(shortKpiLabel(q, lang, t), '—', ` / ${max}`)
    }
    return kpiCell(shortKpiLabel(q, lang, t), `${value}`, ` / ${max}`)
  })

  // Eerste 2 cellen vast (Responses, NPS), dan max 6 scale-cellen verdeeld over
  // 2 rijen van 4. Als er meer dan 6 scale-vragen zijn, knippen we af — dat houdt
  // het rapport-layout consistent met de bestaande look.
  const visible = scaleCells.slice(0, 6)
  // Pad tot 6 met onzichtbare lege cellen zodat de tabel-layout stabiel blijft
  while (visible.length < 6) {
    visible.push(kpiCell('', '', ''))
  }

  const row1 = new TableRow({
    cantSplit: true,
    children: [
      kpiCell(t.kpiResponses, `${n}`),
      kpiCell(t.kpiNps, `${nps}`),
      visible[0],
      visible[1],
    ],
  })
  const row2 = new TableRow({
    cantSplit: true,
    children: [visible[2], visible[3], visible[4], visible[5]],
  })

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 240 },
      children: [new TextRun({ text: t.kpiTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [row1, row2],
    }),
    emptyP(),
  ]
}

function buildScoresTable(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  questions: SurveyQuestion[] = [],
): (Paragraph | Table)[] {
  // Survey-aware: alle scale-vragen uit de snapshot, in display_order.
  // We tonen ALLE scale-vragen — ook degene zonder antwoorden — zodat het rapport
  // het volledige onderzoeksdesign reflecteert (i.t.v. KPI-tegels die compacter
  // moeten blijven). Lege vragen krijgen "—" i.p.v. een misleidend 0.
  const dims = questions
    .filter(q => q.type === 'scale')
    .map(q => ({
      label: shortKpiLabel(q, lang, t),
      code: q.code,
      max: q.scale_max ?? 5,
    }))

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: [
      new TableCell({
        width: { size: 35, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('Dimensie / Dimension', { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 50, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('', { size: 20 })],
      }),
      new TableCell({
        width: { size: 15, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('Score', { bold: true, size: 20, alignment: AlignmentType.CENTER } as any)],
      }),
    ],
  })

  const bodyRows = dims.map(d => {
    const { value: score, count } = avgFor(rows, d.code)
    const hasData = count > 0
    return new TableRow({
      cantSplit: true,
      children: [
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 120, bottom: 120, left: 200, right: 100 },
          children: [p(d.label, { italics: true, size: 22 })],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 120, bottom: 120, left: 200, right: 200 },
          children: [
            new Paragraph({
              children: [new TextRun({
                text: hasData ? bar(score, d.max, 32) : '',
                color: COLORS.teal,
                font: 'Consolas',
              })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 120, bottom: 120, left: 100, right: 200 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({
                text: hasData ? `${score} / ${d.max}` : '— / ' + d.max,
                bold: true,
                color: hasData ? COLORS.tealDark : COLORS.inkSoft,
                italics: !hasData,
                size: 22,
              })],
            }),
          ],
        }),
      ],
    })
  })

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 200 },
      children: [new TextRun({ text: t.scoresTitle, bold: true, color: COLORS.tealDark, size: 28 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...bodyRows],
    }),
    emptyP(),
  ]
}

function buildNpsSection(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  questions: SurveyQuestion[] = [],
): (Paragraph | Table)[] {
  // Survey-aware NPS: gebruik de NPS-vraag uit de snapshot (kan in theorie afwijken
  // van q1_nps). Als er geen NPS-vraag is, skip de hele sectie.
  const npsQ = questions.find(q => q.type === 'nps')
  if (!npsQ && questions.length > 0) {
    // Snapshot beschikbaar maar geen NPS-vraag → niets te tonen
    return []
  }
  const { dist, promoters, passives, detractors, total, nps, min } = npsBreakdown(rows, questions)
  const maxBar = Math.max(...dist, 1)

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: [
      new TableCell({
        width: { size: 12, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.npsScore, { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 18, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.npsCategory, { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 55, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('', { size: 20 })],
      }),
      new TableCell({
        width: { size: 15, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.npsCount, { bold: true, size: 20 })],
      }),
    ],
  })

  const distRows = dist.map((count, i) => {
    // 'score' = werkelijke waarde op de NPS-schaal (min..max), niet array-index.
    // Bij standaard 0-10 schaal is min=0 dus score===i; bij afwijkende schalen
    // (theoretisch) verschuift dit netjes mee.
    const score = min + i
    let cat = t.npsDetractors
    let color = COLORS.red
    if (score >= 9) { cat = t.npsPromoters; color = COLORS.green }
    else if (score >= 7) { cat = t.npsPassives; color = COLORS.orange }

    return new TableRow({
      cantSplit: true,
      children: [
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 160, right: 100 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text: `${score}`, bold: true, size: 22 })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 160, right: 100 },
          children: [
            new Paragraph({
              children: [new TextRun({ text: cat, color, italics: true, size: 18 })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 200, right: 200 },
          children: [
            new Paragraph({
              children: [new TextRun({ text: bar(count, maxBar, 30), color, font: 'Consolas' })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 100, right: 200 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text: `${count}`, bold: true, size: 22 })],
            }),
          ],
        }),
      ],
    })
  })

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.npsTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Paragraph({
      spacing: { after: 200 },
      children: [new TextRun({
        text: `${t.npsPromoters}: ${promoters}/${total} · ${t.npsPassives}: ${passives}/${total} · ${t.npsDetractors}: ${detractors}/${total}  →  NPS = ${nps}`,
        italics: true,
        color: COLORS.inkSoft,
        size: 20,
      })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...distRows],
    }),
    emptyP(),
  ]
}

function buildAttendanceSection(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  questions: SurveyQuestion[] = [],
): (Paragraph | Table)[] {
  // Survey-aware: gebruik de eerste choice-vraag uit de snapshot (typisch
  // "hoeveel concerten bijgewoond?" voor Reeks I, mogelijk iets anders voor
  // andere surveys — of helemaal niets). Als er geen choice-vraag is, skip.
  const choiceQ = questions.find(q => q.type === 'choice' && !/contact|email|naam/i.test(q.code))
  if (!choiceQ && questions.length > 0) return []

  const data = choiceQ
    ? choiceBreakdown(rows, choiceQ)
    : ((): { label: string; count: number }[] => {
        // Legacy fallback: oude q3_aantal kolom (geen snapshot beschikbaar)
        const counts: Record<string, number> = {}
        rows.forEach(r => {
          const v = (r as any).q3_aantal
          if (v) counts[v] = (counts[v] || 0) + 1
        })
        const labelFor = (k: string) =>
          (k === 'alle 6' || k === 'all 6') ? (lang === 'en' ? 'all 6' : 'alle 6') : k
        const ordered = ['1', '2', '3', '4', '5', 'alle 6', 'all 6']
        const seen = new Set<string>()
        const out: { label: string; count: number }[] = []
        for (const k of ordered) {
          if (counts[k] && !seen.has(k)) {
            out.push({ label: labelFor(k), count: counts[k] })
            seen.add(k)
          }
        }
        for (const k of Object.keys(counts)) {
          if (!seen.has(k)) out.push({ label: k, count: counts[k] })
        }
        return out
      })()

  if (data.length === 0) return []
  const max = Math.max(...data.map(d => d.count), 1)
  // Sectie-titel: gebruik label van de choice-vraag als die uit snapshot komt
  const sectionTitle = choiceQ
    ? ((lang === 'en' ? choiceQ.label_en : choiceQ.label_nl) || t.attendanceTitle)
    : t.attendanceTitle

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: [
      new TableCell({
        width: { size: 25, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.attendanceLabel, { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 60, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('', { size: 20 })],
      }),
      new TableCell({
        width: { size: 15, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.attendanceCount, { bold: true, size: 20 })],
      }),
    ],
  })

  const dataRows = data.map(({ label, count }) =>
    new TableRow({
      cantSplit: true,
      children: [
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 100, bottom: 100, left: 200, right: 100 },
          children: [p(label, { italics: true, size: 22 })],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 100, bottom: 100, left: 200, right: 200 },
          children: [
            new Paragraph({
              children: [new TextRun({ text: bar(count, max, 30), color: COLORS.teal, font: 'Consolas' })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 100, bottom: 100, left: 100, right: 200 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text: `${count}`, bold: true, size: 22 })],
            }),
          ],
        }),
      ],
    })
  )

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: sectionTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...dataRows],
    }),
    emptyP(),
  ]
}

function buildAiSection(analysis: AnalysisResult | null, lang: Lang, t: ReturnType<typeof L>): Paragraph[] {
  const out: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.aiTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
  ]

  if (!analysis) {
    out.push(p(t.aiNoData, { italics: true, color: COLORS.inkSoft, size: 22 }))
    return out
  }

  out.push(new Paragraph({
    spacing: { after: 240 },
    children: [new TextRun({
      text: t.aiMeta(analysis.response_count, fmtDateTime(analysis.generated_at, lang), analysis.provider || ''),
      italics: true, color: COLORS.inkSoft, size: 18,
    })],
  }))

  // Summary
  if (analysis.samenvatting) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiSummary, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    out.push(new Paragraph({
      spacing: { after: 200 },
      children: [new TextRun({ text: analysis.samenvatting, size: 22 })],
    }))
  }

  // Strong points
  if (analysis.sterke_punten?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiStrong, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.sterke_punten.forEach(s => {
      out.push(new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 60 },
        keepLines: true,
        children: [new TextRun({ text: s.punt, bold: true, size: 22 })],
      }))
      if (s.bewijs) out.push(new Paragraph({
        spacing: { after: 120 },
        indent: { left: 360 },
        children: [new TextRun({ text: s.bewijs, italics: true, color: COLORS.inkSoft, size: 20 })],
      }))
    })
  }

  // Improvements
  if (analysis.verbeterpunten?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiImprove, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.verbeterpunten.forEach(s => {
      out.push(new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 60 },
        keepLines: true,
        children: [new TextRun({ text: s.punt, bold: true, size: 22 })],
      }))
      if (s.bewijs) out.push(new Paragraph({
        spacing: { after: 120 },
        indent: { left: 360 },
        children: [new TextRun({ text: s.bewijs, italics: true, color: COLORS.inkSoft, size: 20 })],
      }))
    })
  }

  // Suggestions
  if (analysis.suggesties_reeks2?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiSuggest, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.suggesties_reeks2.forEach(s => {
      out.push(new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 60 },
        keepLines: true,
        children: [new TextRun({ text: s.titel, bold: true, size: 22 })],
      }))
      if (s.beschrijving) out.push(new Paragraph({
        spacing: { after: 120 },
        indent: { left: 360 },
        children: [new TextRun({ text: s.beschrijving, italics: true, color: COLORS.inkSoft, size: 20 })],
      }))
    })
  }

  // Quotes
  if (analysis.citaten?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiQuotes, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.citaten.forEach(q => {
      const sentLabel = q.sentiment === 'positief' ? t.sentimentPositive
        : q.sentiment === 'kritisch' ? t.sentimentCritical
        : t.sentimentNeutral
      const sentColor = q.sentiment === 'positief' ? COLORS.green
        : q.sentiment === 'kritisch' ? COLORS.red
        : COLORS.inkSoft
      out.push(new Paragraph({
        spacing: { after: 60 },
        indent: { left: 360 },
        keepLines: true,
        children: [new TextRun({ text: `"${q.tekst}"`, italics: true, size: 22 })],
      }))
      out.push(new Paragraph({
        spacing: { after: 200 },
        indent: { left: 360 },
        children: [
          new TextRun({ text: `${q.vraag || ''} · `, color: COLORS.inkSoft, size: 18 }),
          new TextRun({ text: sentLabel, color: sentColor, italics: true, size: 18 }),
        ],
      }))
    })
  }

  return out
}

function buildOpenAnswersSection(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  questions: SurveyQuestion[] = [],
): Paragraph[] {
  // Survey-aware: itereer over ALLE text/paragraph vragen uit de snapshot,
  // in display_order. Skip de "naam" / "email" vragen want die zijn niet
  // analytisch interessant en geven privacy-leakage in een rapport.
  const openQs = questions
    .filter(q => (q.type === 'text' || q.type === 'paragraph') && !/naam|name|email/i.test(q.code))
    .map(q => ({
      code: q.code,
      // Label-formaat consistent met de oude versie: "Q2 — Wat blijft je bij?"
      label: `${q.code.toUpperCase()} — ${(lang === 'en' ? q.label_en : q.label_nl) || q.code}`,
    }))

  // Bepaal welke NPS-code we tonen in de meta-regel onder elk antwoord
  const npsCode = questions.find(q => q.type === 'nps')?.code ?? 'q1_nps'

  const out: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.openTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
  ]

  if (openQs.length === 0) {
    out.push(p(lang === 'en' ? 'No open questions in this survey.' : 'Geen open vragen in deze enquête.', {
      italics: true, color: COLORS.inkSoft, size: 20,
    }))
    return out
  }

  openQs.forEach(q => {
    const answers = rows
      .map(r => {
        const v = getAnswer(r, q.code)
        const npsV = getAnswer(r, npsCode)
        return {
          text: typeof v === 'string' ? v : '',
          date: r.submitted_at,
          nps: typeof npsV === 'number' || typeof npsV === 'string' ? String(npsV) : '—',
        }
      })
      .filter(a => a.text && a.text.trim().length > 0)

    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [
        new TextRun({ text: q.label, bold: true, color: COLORS.tealDark, size: 24 }),
        new TextRun({ text: `   (${answers.length})`, italics: true, color: COLORS.inkSoft, size: 18 }),
      ],
    }))

    if (answers.length === 0) {
      out.push(p(t.openNoneFor(q.label), { italics: true, color: COLORS.inkSoft, size: 20 }))
      return
    }

    answers.forEach(a => {
      out.push(new Paragraph({
        spacing: { after: 40 },
        keepLines: true,
        children: [new TextRun({ text: a.text, size: 22 })],
      }))
      out.push(new Paragraph({
        spacing: { after: 160 },
        children: [new TextRun({
          text: `${fmtDateTime(a.date, lang)} · NPS ${a.nps}`,
          italics: true, color: COLORS.inkSoft, size: 16,
        })],
      }))
    })
  })

  return out
}

/**
 * Korte kolomheader voor de raw-data tabel: probeer een Reeks-I i18n-string,
 * anders een afkorting van het label.
 */
function rawHeaderFor(q: SurveyQuestion, lang: Lang, t: ReturnType<typeof L>): string {
  const map: Record<string, string> = {
    q1_nps: t.rawNps,
    q3_aantal: t.rawConcerts,
    q4_sfeer: t.rawAtmosphere,
    q6_akoestiek: t.rawAcoustics,
    q8_repertoire: t.rawRepertoire,
    q10_interactie: t.rawJos,
    q12_communic: t.rawComms,
    q14_bijdrage: t.rawContribution,
    q19_naam: t.rawName,
  }
  if (map[q.code]) return map[q.code]
  // Compact header: gewoon de code, want lange labels passen niet in landscape-tabel
  return q.code.toUpperCase()
}

function buildRawDataSection(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  questions: SurveyQuestion[] = [],
): (Paragraph | Table)[] {
  // Survey-aware kolommen: Datum + NPS + alle scale + eerste choice + naam-vraag.
  // Beperk tot max 11 kolommen om in landscape-A4 leesbaar te blijven (~25mm/kolom).
  const npsQ = questions.find(q => q.type === 'nps')
  const choiceQ = questions.find(q => q.type === 'choice' && !/contact|email/i.test(q.code))
  const scaleQs = questions.filter(q => q.type === 'scale')
  const nameQ = questions.find(q => q.type === 'text' && /naam|name/i.test(q.code))

  // Build column-list — Datum altijd eerste, daarna gestructureerd
  const cols: Array<{ header: string; getCell: (r: ResponseRow) => string; bold?: boolean }> = []
  cols.push({
    header: t.rawDate,
    getCell: (r) => fmtDateTime(r.submitted_at, lang),
  })
  if (npsQ) {
    cols.push({
      header: rawHeaderFor(npsQ, lang, t),
      getCell: (r) => {
        const v = getAnswer(r, npsQ.code)
        return v == null ? '—' : String(v)
      },
      bold: true,
    })
  }
  if (choiceQ) {
    cols.push({
      header: rawHeaderFor(choiceQ, lang, t),
      getCell: (r) => {
        const v = getAnswer(r, choiceQ.code)
        return v == null ? '—' : String(v)
      },
    })
  }
  // Scale-vragen — beperken tot eerste 6 om tabel werkbaar te houden
  const maxScales = nameQ ? 6 : 8 // als er een naam-kolom volgt, één scale minder
  for (const q of scaleQs.slice(0, maxScales)) {
    cols.push({
      header: rawHeaderFor(q, lang, t),
      getCell: (r) => {
        const v = getAnswer(r, q.code)
        return v == null ? '—' : String(v)
      },
    })
  }
  if (nameQ) {
    cols.push({
      header: rawHeaderFor(nameQ, lang, t),
      getCell: (r) => {
        const v = getAnswer(r, nameQ.code)
        return v == null ? '—' : String(v)
      },
    })
  }

  // Fallback voor surveys zonder snapshot (legacy Reeks I)
  if (questions.length === 0) {
    const fallbackHeaders = [
      t.rawDate, t.rawNps, t.rawConcerts, t.rawAtmosphere, t.rawAcoustics, t.rawRepertoire,
      t.rawJos, t.rawComms, t.rawContribution, t.rawName,
    ]
    const legacyKeys = ['q1_nps', 'q3_aantal', 'q4_sfeer', 'q6_akoestiek', 'q8_repertoire',
                        'q10_interactie', 'q12_communic', 'q14_bijdrage', 'q19_naam']
    cols.length = 0
    cols.push({ header: fallbackHeaders[0], getCell: r => fmtDateTime(r.submitted_at, lang) })
    legacyKeys.forEach((k, i) => {
      cols.push({
        header: fallbackHeaders[i + 1],
        getCell: r => {
          const v = (r as any)[k]
          return v == null ? '—' : String(v)
        },
        bold: i === 0,
      })
    })
  }

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: cols.map(c =>
      new TableCell({
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        margins: { top: 80, bottom: 80, left: 100, right: 100 },
        children: [p(c.header, { bold: true, size: 16 })],
      })
    ),
  })

  const dataRows = rows.map(r =>
    new TableRow({
      cantSplit: true,
      children: cols.map(c =>
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(c.getCell(r), { bold: c.bold, size: 16 })],
        })
      ),
    })
  )

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.rawTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...dataRows],
    }),
  ]
}

// ===== Main entry =====
/**
 * Bouw een volledig Word-rapport voor één survey.
 *
 * @param rows      antwoord-rijen voor deze survey
 * @param analysis  optionele AI-analyse (uit cache)
 * @param lang      'nl' | 'en'
 * @param survey    optionele survey-metadata (titel, artiest…)
 * @param questions per-survey vragen-snapshot (uit survey_questions, display order).
 *                  Als leeg, valt het rapport terug op de oude q1..q20 hardcoded
 *                  layout — handig voor backwards-compat met cached/oudere data.
 */
export async function buildSurveyDocx(
  rows: ResponseRow[],
  analysis: AnalysisResult | null,
  lang: Lang,
  survey?: Survey,
  questions: SurveyQuestion[] = [],
): Promise<Uint8Array> {
  const t = L(lang)

  const sections = [
    // Section 1: cover (landscape, no header/footer)
    {
      properties: {
        page: {
          size: { orientation: PageOrientation.LANDSCAPE },
          margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 }, // 1 inch
        },
      },
      children: buildCover(rows, lang, t, survey),
    },
    // Section 2: rest of the report (landscape with header/footer + page numbers)
    {
      properties: {
        page: {
          size: { orientation: PageOrientation.LANDSCAPE },
          margin: { top: 1080, bottom: 1080, left: 1080, right: 1080 }, // 0.75 inch
        },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              alignment: AlignmentType.RIGHT,
              children: [new TextRun({ text: t.footer, italics: true, color: COLORS.inkSoft, size: 16 })],
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: `${t.page} `, italics: true, color: COLORS.inkSoft, size: 16 }),
                new TextRun({ children: [PageNumber.CURRENT], italics: true, color: COLORS.inkSoft, size: 16 }),
                new TextRun({ text: ` ${t.of} `, italics: true, color: COLORS.inkSoft, size: 16 }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], italics: true, color: COLORS.inkSoft, size: 16 }),
              ],
            }),
          ],
        }),
      },
      children: [
        ...buildKpiSection(rows, lang, t, questions),
        ...buildScoresTable(rows, lang, t, questions),
        ...buildNpsSection(rows, lang, t, questions),
        ...buildAttendanceSection(rows, lang, t, questions),
        ...buildAiSection(analysis, lang, t),
        ...buildOpenAnswersSection(rows, lang, t, questions),
        ...buildRawDataSection(rows, lang, t, questions),
      ],
    },
  ]

  const doc = new Document({
    creator: 'Pensato.org survey dashboard',
    title: t.coverTitle,
    description: t.coverSub,
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
        },
      },
    },
    sections,
  })

  // Packer.toBuffer returns a Uint8Array in browser/edge runtimes
  const buffer = await Packer.toBuffer(doc)
  return buffer as Uint8Array
}
