// Word (.docx) report builder for the Huiskamerconcerten survey dashboard.
// Produces a single editable document with: cover page, KPI summary,
// NPS distribution, attendance, AI analysis (NL/EN), open answers,
// and raw data table. Pure server-side, runs in Cloudflare Workers.

import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  PageOrientation,
  Header,
  Footer,
  PageNumber,
  ShadingType,
} from 'docx'
import type { ResponseRow } from './db'
import type { AnalysisResult } from './ai'
import type { Survey } from './surveys'

type Lang = 'nl' | 'en'

// ===== Color palette (matches dashboard) =====
const COLORS = {
  teal: '1F8F8F',
  tealDark: '146060',
  ink: '2C2A28',
  inkSoft: '5C5852',
  border: 'D4CDB8',
  cream: 'FBF8F2',
  paper: 'F4EEDF',
  green: '2E7D32',
  orange: 'F4A93C',
  red: 'B73229',
}

// ===== i18n helpers =====
function L(lang: Lang) {
  if (lang === 'en') {
    return {
      coverBadge: 'Pensato.org',
      coverTitle: 'Survey report — Series I',
      coverSub: 'House concerts · Jos van Immerseel & Ayako Ito',
      coverResponses: 'Responses',
      coverNps: 'NPS',
      coverDate: 'Date',
      coverCredit: 'Generated by the Pensato.org survey dashboard',
      kpiTitle: 'Key indicators',
      kpiResponses: 'Responses',
      kpiNps: 'NPS score',
      kpiAtmosphere: 'Atmosphere (Q4)',
      kpiAcoustics: 'Acoustics (Q6)',
      kpiRepertoire: 'Repertoire (Q8)',
      kpiInteraction: 'Interaction (Q10)',
      kpiComms: 'Communication (Q12)',
      kpiContribution: 'Contribution (Q14)',
      scoresTitle: 'Average scores per dimension',
      npsTitle: 'NPS distribution',
      npsScore: 'Score',
      npsCount: 'Count',
      npsCategory: 'Category',
      npsDetractors: 'Detractors',
      npsPassives: 'Passives',
      npsPromoters: 'Promoters',
      attendanceTitle: 'Concert attendance',
      attendanceLabel: '# concerts',
      attendanceCount: 'Visitors',
      aiTitle: 'AI analysis & suggestions for Series II',
      aiMeta: (n: number, date: string, provider: string) => `Based on ${n} responses · generated on ${date}${provider ? ' · ' + provider : ''}`,
      aiSummary: 'Summary',
      aiStrong: 'Strengths',
      aiImprove: 'Areas for improvement',
      aiSuggest: 'Concrete suggestions for Series II',
      aiQuotes: 'Selected quotes',
      aiNoData: 'No AI analysis available yet. Generate one in the dashboard first.',
      openTitle: 'Open answers',
      openNoneFor: (q: string) => `No answers for ${q}.`,
      rawTitle: 'Raw data (anonymous)',
      rawDate: 'Date',
      rawNps: 'NPS',
      rawConcerts: '# concerts',
      rawAtmosphere: 'Atmosphere',
      rawAcoustics: 'Acoustics',
      rawRepertoire: 'Repertoire',
      rawJos: 'Jos',
      rawComms: 'Comm.',
      rawContribution: 'Contrib.',
      rawName: 'Name',
      footer: 'Huiskamerconcerten Reeks I · Pensato.org',
      page: 'Page',
      of: 'of',
      sentimentPositive: 'positive',
      sentimentNeutral: 'neutral',
      sentimentCritical: 'critical',
    }
  }
  return {
    coverBadge: 'Pensato.org',
    coverTitle: 'Surveyrapport — Reeks I',
    coverSub: 'Huiskamerconcerten · Jos van Immerseel & Ayako Ito',
    coverResponses: 'Responses',
    coverNps: 'NPS',
    coverDate: 'Datum',
    coverCredit: 'Gegenereerd door het Pensato.org surveydashboard',
    kpiTitle: 'Kerncijfers',
    kpiResponses: 'Responses',
    kpiNps: 'NPS-score',
    kpiAtmosphere: 'Sfeer (Q4)',
    kpiAcoustics: 'Akoestiek (Q6)',
    kpiRepertoire: 'Repertoire (Q8)',
    kpiInteraction: 'Interactie (Q10)',
    kpiComms: 'Communicatie (Q12)',
    kpiContribution: 'Bijdrage (Q14)',
    scoresTitle: 'Gemiddelde scores per dimensie',
    npsTitle: 'NPS-verdeling',
    npsScore: 'Score',
    npsCount: 'Aantal',
    npsCategory: 'Categorie',
    npsDetractors: 'Detractors',
    npsPassives: 'Passives',
    npsPromoters: 'Promoters',
    attendanceTitle: 'Concertdeelname',
    attendanceLabel: '# concerten',
    attendanceCount: 'Bezoekers',
    aiTitle: 'AI-analyse & suggesties voor Reeks II',
    aiMeta: (n: number, date: string, provider: string) => `Op basis van ${n} responses · gegenereerd op ${date}${provider ? ' · ' + provider : ''}`,
    aiSummary: 'Samenvatting',
    aiStrong: 'Sterke punten',
    aiImprove: 'Verbeterpunten',
    aiSuggest: 'Concrete suggesties voor Reeks II',
    aiQuotes: 'Geselecteerde citaten',
    aiNoData: 'Nog geen AI-analyse beschikbaar. Genereer er eerst een in het dashboard.',
    openTitle: 'Open antwoorden',
    openNoneFor: (q: string) => `Geen antwoorden voor ${q}.`,
    rawTitle: 'Ruwe data (anoniem)',
    rawDate: 'Datum',
    rawNps: 'NPS',
    rawConcerts: '# concerten',
    rawAtmosphere: 'Sfeer',
    rawAcoustics: 'Akoestiek',
    rawRepertoire: 'Repertoire',
    rawJos: 'Jos',
    rawComms: 'Comm.',
    rawContribution: 'Bijdrage',
    rawName: 'Naam',
    footer: 'Huiskamerconcerten Reeks I · Pensato.org',
    page: 'Pagina',
    of: 'van',
    sentimentPositive: 'positief',
    sentimentNeutral: 'neutraal',
    sentimentCritical: 'kritisch',
  }
}

// ===== Helpers =====
const round1 = (v: number) => Math.round(v * 10) / 10

function avg(rows: ResponseRow[], key: keyof ResponseRow): number {
  const vals = rows.map(r => r[key]).filter(v => typeof v === 'number') as number[]
  if (vals.length === 0) return 0
  return round1(vals.reduce((a, b) => a + b, 0) / vals.length)
}

function npsBreakdown(rows: ResponseRow[]) {
  const scores = rows.map(r => r.q1_nps).filter(v => typeof v === 'number')
  const total = scores.length || 1
  const promoters = scores.filter(v => v >= 9).length
  const passives = scores.filter(v => v >= 7 && v <= 8).length
  const detractors = scores.filter(v => v <= 6).length
  const nps = scores.length === 0
    ? 0
    : Math.round(((promoters / scores.length) - (detractors / scores.length)) * 100)
  // Distribution per score 0..10
  const dist: number[] = Array.from({ length: 11 }, (_, i) => scores.filter(v => v === i).length)
  return { promoters, passives, detractors, nps, dist, total }
}

function attendanceMap(rows: ResponseRow[], lang: Lang): { label: string; count: number }[] {
  const counts: Record<string, number> = {}
  rows.forEach(r => { if (r.q3_aantal) counts[r.q3_aantal] = (counts[r.q3_aantal] || 0) + 1 })
  const labelFor = (k: string) => {
    if (k === 'alle 6' || k === 'all 6') return lang === 'en' ? 'all 6' : 'alle 6'
    return k
  }
  const ordered = ['1', '2', '3', '4', '5', 'alle 6', 'all 6']
  const seen = new Set<string>()
  const out: { label: string; count: number }[] = []
  ordered.forEach(k => {
    if (counts[k] && !seen.has(k)) {
      out.push({ label: labelFor(k), count: counts[k] })
      seen.add(k)
    }
  })
  // Append any unexpected keys
  Object.keys(counts).forEach(k => {
    if (!seen.has(k)) out.push({ label: k, count: counts[k] })
  })
  return out
}

function fmtDate(iso: string, lang: Lang): string {
  try {
    const d = new Date(iso)
    return d.toLocaleDateString(lang === 'en' ? 'en-GB' : 'nl-BE', { day: '2-digit', month: 'long', year: 'numeric' })
  } catch { return iso }
}

function fmtDateTime(iso: string, lang: Lang): string {
  try {
    const d = new Date(iso)
    return d.toLocaleString(lang === 'en' ? 'en-GB' : 'nl-BE', {
      day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit',
    })
  } catch { return iso }
}

// ===== Reusable docx primitives =====
const NO_BORDER = {
  top:    { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  bottom: { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  left:   { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
  right:  { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' },
}

const LIGHT_BORDER = {
  top:    { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
  bottom: { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
  left:   { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
  right:  { style: BorderStyle.SINGLE, size: 4, color: COLORS.border },
}

function p(text: string, opts: any = {}): Paragraph {
  return new Paragraph({
    spacing: { after: 100, ...(opts.spacing || {}) },
    alignment: opts.alignment,
    heading: opts.heading,
    children: [new TextRun({
      text,
      bold: opts.bold,
      italics: opts.italics,
      color: opts.color,
      size: opts.size, // half-points
      font: opts.font,
    })],
  })
}

function emptyP(): Paragraph {
  return new Paragraph({ children: [new TextRun({ text: '' })] })
}

function bullet(text: string, lang: Lang, italic = false): Paragraph {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text, italics: italic })],
  })
}

function kpiCell(label: string, value: string, suffix = ''): TableCell {
  return new TableCell({
    width: { size: 25, type: WidthType.PERCENTAGE },
    margins: { top: 200, bottom: 200, left: 220, right: 220 },
    shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.cream },
    borders: LIGHT_BORDER,
    children: [
      new Paragraph({
        spacing: { after: 60 },
        children: [new TextRun({ text: label, italics: true, size: 18, color: COLORS.inkSoft })],
      }),
      new Paragraph({
        spacing: { after: 40 },
        children: [
          new TextRun({ text: value, bold: true, size: 36, color: COLORS.tealDark }),
          new TextRun({ text: suffix, size: 18, color: COLORS.inkSoft }),
        ],
      }),
    ],
  })
}

// Horizontal "bar" rendered as a simple unicode block string scaled to the value
function bar(value: number, max: number, width = 30): string {
  if (max <= 0) return ''
  const filled = Math.max(0, Math.round((value / max) * width))
  return '█'.repeat(filled) + '░'.repeat(Math.max(0, width - filled))
}

// ===== Section builders =====

function buildCover(
  rows: ResponseRow[],
  lang: Lang,
  t: ReturnType<typeof L>,
  survey?: Survey,
): Paragraph[] {
  const n = rows.length
  const { nps } = npsBreakdown(rows)
  const today = new Date().toLocaleDateString(lang === 'en' ? 'en-GB' : 'nl-BE', {
    day: '2-digit', month: 'long', year: 'numeric',
  })
  const badge = survey?.series_name ?? t.coverBadge
  const title = survey ? (lang === 'en' ? survey.title_en : survey.title_nl) : t.coverTitle
  const sub = survey
    ? ((lang === 'en' ? survey.subtitle_en : survey.subtitle_nl) ?? t.coverSub)
    : t.coverSub

  return [
    new Paragraph({ children: [new TextRun({ text: '' })], spacing: { before: 1800 } }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [new TextRun({ text: badge, italics: true, color: COLORS.tealDark, size: 22 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [new TextRun({ text: title, bold: true, color: COLORS.tealDark, size: 56 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
      children: [new TextRun({ text: sub, italics: true, color: COLORS.inkSoft, size: 26 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: `${n}`, bold: true, size: 40, color: COLORS.ink }),
        new TextRun({ text: '   ·   ', color: COLORS.inkSoft, size: 32 }),
        new TextRun({ text: `${nps}`, bold: true, size: 40, color: COLORS.ink }),
        new TextRun({ text: '   ·   ', color: COLORS.inkSoft, size: 32 }),
        new TextRun({ text: today, bold: true, italics: true, size: 32, color: COLORS.ink }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 1600 },
      children: [
        new TextRun({ text: t.coverResponses, color: COLORS.inkSoft, size: 18 }),
        new TextRun({ text: '            ', size: 18 }),
        new TextRun({ text: t.coverNps, color: COLORS.inkSoft, size: 18 }),
        new TextRun({ text: '                ', size: 18 }),
        new TextRun({ text: t.coverDate, color: COLORS.inkSoft, size: 18 }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
      pageBreakBefore: false,
      children: [new TextRun({ text: t.coverCredit, italics: true, color: COLORS.inkSoft, size: 18 })],
    }),
  ]
}

function buildKpiSection(rows: ResponseRow[], lang: Lang, t: ReturnType<typeof L>): (Paragraph | Table)[] {
  const n = rows.length
  const { nps } = npsBreakdown(rows)

  const row1 = new TableRow({
    cantSplit: true,
    children: [
      kpiCell(t.kpiResponses, `${n}`),
      kpiCell(t.kpiNps, `${nps}`),
      kpiCell(t.kpiAtmosphere, `${avg(rows, 'q4_sfeer')}`, ' / 5'),
      kpiCell(t.kpiAcoustics, `${avg(rows, 'q6_akoestiek')}`, ' / 5'),
    ],
  })
  const row2 = new TableRow({
    cantSplit: true,
    children: [
      kpiCell(t.kpiRepertoire, `${avg(rows, 'q8_repertoire')}`, ' / 5'),
      kpiCell(t.kpiInteraction, `${avg(rows, 'q10_interactie')}`, ' / 5'),
      kpiCell(t.kpiComms, `${avg(rows, 'q12_communic')}`, ' / 5'),
      kpiCell(t.kpiContribution, `${avg(rows, 'q14_bijdrage')}`, ' / 5'),
    ],
  })

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 240 },
      children: [new TextRun({ text: t.kpiTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [row1, row2],
    }),
    emptyP(),
  ]
}

function buildScoresTable(rows: ResponseRow[], lang: Lang, t: ReturnType<typeof L>): (Paragraph | Table)[] {
  const dims: { label: string; key: keyof ResponseRow }[] = [
    { label: t.kpiAtmosphere,  key: 'q4_sfeer' },
    { label: t.kpiAcoustics,   key: 'q6_akoestiek' },
    { label: t.kpiRepertoire,  key: 'q8_repertoire' },
    { label: t.kpiInteraction, key: 'q10_interactie' },
    { label: t.kpiComms,       key: 'q12_communic' },
    { label: t.kpiContribution,key: 'q14_bijdrage' },
  ]

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: [
      new TableCell({
        width: { size: 35, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('Dimensie / Dimension', { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 50, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('', { size: 20 })],
      }),
      new TableCell({
        width: { size: 15, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('Score / 5', { bold: true, size: 20, alignment: AlignmentType.CENTER } as any)],
      }),
    ],
  })

  const bodyRows = dims.map(d => {
    const score = avg(rows, d.key)
    return new TableRow({
      cantSplit: true,
      children: [
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 120, bottom: 120, left: 200, right: 100 },
          children: [p(d.label, { italics: true, size: 22 })],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 120, bottom: 120, left: 200, right: 200 },
          children: [
            new Paragraph({
              children: [new TextRun({ text: bar(score, 5, 32), color: COLORS.teal, font: 'Consolas' })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 120, bottom: 120, left: 100, right: 200 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text: `${score}`, bold: true, color: COLORS.tealDark, size: 24 })],
            }),
          ],
        }),
      ],
    })
  })

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 200 },
      children: [new TextRun({ text: t.scoresTitle, bold: true, color: COLORS.tealDark, size: 28 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...bodyRows],
    }),
    emptyP(),
  ]
}

function buildNpsSection(rows: ResponseRow[], lang: Lang, t: ReturnType<typeof L>): (Paragraph | Table)[] {
  const { dist, promoters, passives, detractors, total, nps } = npsBreakdown(rows)
  const maxBar = Math.max(...dist, 1)

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: [
      new TableCell({
        width: { size: 12, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.npsScore, { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 18, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.npsCategory, { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 55, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('', { size: 20 })],
      }),
      new TableCell({
        width: { size: 15, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.npsCount, { bold: true, size: 20 })],
      }),
    ],
  })

  const distRows = dist.map((count, score) => {
    let cat = t.npsDetractors
    let color = COLORS.red
    if (score >= 9) { cat = t.npsPromoters; color = COLORS.green }
    else if (score >= 7) { cat = t.npsPassives; color = COLORS.orange }

    return new TableRow({
      cantSplit: true,
      children: [
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 160, right: 100 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text: `${score}`, bold: true, size: 22 })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 160, right: 100 },
          children: [
            new Paragraph({
              children: [new TextRun({ text: cat, color, italics: true, size: 18 })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 200, right: 200 },
          children: [
            new Paragraph({
              children: [new TextRun({ text: bar(count, maxBar, 30), color, font: 'Consolas' })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 80, bottom: 80, left: 100, right: 200 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text: `${count}`, bold: true, size: 22 })],
            }),
          ],
        }),
      ],
    })
  })

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.npsTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Paragraph({
      spacing: { after: 200 },
      children: [new TextRun({
        text: `${t.npsPromoters}: ${promoters}/${total} · ${t.npsPassives}: ${passives}/${total} · ${t.npsDetractors}: ${detractors}/${total}  →  NPS = ${nps}`,
        italics: true,
        color: COLORS.inkSoft,
        size: 20,
      })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...distRows],
    }),
    emptyP(),
  ]
}

function buildAttendanceSection(rows: ResponseRow[], lang: Lang, t: ReturnType<typeof L>): (Paragraph | Table)[] {
  const data = attendanceMap(rows, lang)
  const max = Math.max(...data.map(d => d.count), 1)

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: [
      new TableCell({
        width: { size: 25, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.attendanceLabel, { bold: true, size: 20 })],
      }),
      new TableCell({
        width: { size: 60, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p('', { size: 20 })],
      }),
      new TableCell({
        width: { size: 15, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        children: [p(t.attendanceCount, { bold: true, size: 20 })],
      }),
    ],
  })

  const dataRows = data.map(({ label, count }) =>
    new TableRow({
      cantSplit: true,
      children: [
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 100, bottom: 100, left: 200, right: 100 },
          children: [p(label, { italics: true, size: 22 })],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 100, bottom: 100, left: 200, right: 200 },
          children: [
            new Paragraph({
              children: [new TextRun({ text: bar(count, max, 30), color: COLORS.teal, font: 'Consolas' })],
            }),
          ],
        }),
        new TableCell({
          borders: LIGHT_BORDER,
          margins: { top: 100, bottom: 100, left: 100, right: 200 },
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ text: `${count}`, bold: true, size: 22 })],
            }),
          ],
        }),
      ],
    })
  )

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.attendanceTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...dataRows],
    }),
    emptyP(),
  ]
}

function buildAiSection(analysis: AnalysisResult | null, lang: Lang, t: ReturnType<typeof L>): Paragraph[] {
  const out: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.aiTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
  ]

  if (!analysis) {
    out.push(p(t.aiNoData, { italics: true, color: COLORS.inkSoft, size: 22 }))
    return out
  }

  out.push(new Paragraph({
    spacing: { after: 240 },
    children: [new TextRun({
      text: t.aiMeta(analysis.response_count, fmtDateTime(analysis.generated_at, lang), analysis.provider || ''),
      italics: true, color: COLORS.inkSoft, size: 18,
    })],
  }))

  // Summary
  if (analysis.samenvatting) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiSummary, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    out.push(new Paragraph({
      spacing: { after: 200 },
      children: [new TextRun({ text: analysis.samenvatting, size: 22 })],
    }))
  }

  // Strong points
  if (analysis.sterke_punten?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiStrong, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.sterke_punten.forEach(s => {
      out.push(new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 60 },
        keepLines: true,
        children: [new TextRun({ text: s.punt, bold: true, size: 22 })],
      }))
      if (s.bewijs) out.push(new Paragraph({
        spacing: { after: 120 },
        indent: { left: 360 },
        children: [new TextRun({ text: s.bewijs, italics: true, color: COLORS.inkSoft, size: 20 })],
      }))
    })
  }

  // Improvements
  if (analysis.verbeterpunten?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiImprove, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.verbeterpunten.forEach(s => {
      out.push(new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 60 },
        keepLines: true,
        children: [new TextRun({ text: s.punt, bold: true, size: 22 })],
      }))
      if (s.bewijs) out.push(new Paragraph({
        spacing: { after: 120 },
        indent: { left: 360 },
        children: [new TextRun({ text: s.bewijs, italics: true, color: COLORS.inkSoft, size: 20 })],
      }))
    })
  }

  // Suggestions
  if (analysis.suggesties_reeks2?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiSuggest, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.suggesties_reeks2.forEach(s => {
      out.push(new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 60 },
        keepLines: true,
        children: [new TextRun({ text: s.titel, bold: true, size: 22 })],
      }))
      if (s.beschrijving) out.push(new Paragraph({
        spacing: { after: 120 },
        indent: { left: 360 },
        children: [new TextRun({ text: s.beschrijving, italics: true, color: COLORS.inkSoft, size: 20 })],
      }))
    })
  }

  // Quotes
  if (analysis.citaten?.length) {
    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [new TextRun({ text: t.aiQuotes, bold: true, color: COLORS.tealDark, size: 26 })],
    }))
    analysis.citaten.forEach(q => {
      const sentLabel = q.sentiment === 'positief' ? t.sentimentPositive
        : q.sentiment === 'kritisch' ? t.sentimentCritical
        : t.sentimentNeutral
      const sentColor = q.sentiment === 'positief' ? COLORS.green
        : q.sentiment === 'kritisch' ? COLORS.red
        : COLORS.inkSoft
      out.push(new Paragraph({
        spacing: { after: 60 },
        indent: { left: 360 },
        keepLines: true,
        children: [new TextRun({ text: `"${q.tekst}"`, italics: true, size: 22 })],
      }))
      out.push(new Paragraph({
        spacing: { after: 200 },
        indent: { left: 360 },
        children: [
          new TextRun({ text: `${q.vraag || ''} · `, color: COLORS.inkSoft, size: 18 }),
          new TextRun({ text: sentLabel, color: sentColor, italics: true, size: 18 }),
        ],
      }))
    })
  }

  return out
}

function buildOpenAnswersSection(rows: ResponseRow[], lang: Lang, t: ReturnType<typeof L>): Paragraph[] {
  const openQs: { key: keyof ResponseRow; label: string }[] = lang === 'en' ? [
    { key: 'q2_blijft_bij',  label: 'Q2 — What stays with you?' },
    { key: 'q5_sfeer_open',  label: 'Q5 — Atmosphere' },
    { key: 'q7_fortepiano',  label: 'Q7 — Fortepiano' },
    { key: 'q9_favoriet',    label: 'Q9 — Favourite concert' },
    { key: 'q11_gesprek',    label: 'Q11 — Room for conversation' },
    { key: 'q13_catering',   label: 'Q13 — Catering' },
    { key: 'q15_wensen_2',   label: 'Q15 — Wishes Series II' },
    { key: 'q16_gasten',     label: 'Q16 — Guest artists' },
    { key: 'q17_terugkomen', label: 'Q17 — Coming back' },
    { key: 'q18_overige',    label: 'Q18 — Other remarks' },
  ] : [
    { key: 'q2_blijft_bij',  label: 'Q2 — Wat blijft je bij?' },
    { key: 'q5_sfeer_open',  label: 'Q5 — Sfeer' },
    { key: 'q7_fortepiano',  label: 'Q7 — Fortepiano' },
    { key: 'q9_favoriet',    label: 'Q9 — Favoriet concert' },
    { key: 'q11_gesprek',    label: 'Q11 — Ruimte voor gesprek' },
    { key: 'q13_catering',   label: 'Q13 — Catering' },
    { key: 'q15_wensen_2',   label: 'Q15 — Wensen Reeks II' },
    { key: 'q16_gasten',     label: 'Q16 — Gastartiesten' },
    { key: 'q17_terugkomen', label: 'Q17 — Terugkomen' },
    { key: 'q18_overige',    label: 'Q18 — Overige' },
  ]

  const out: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.openTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
  ]

  openQs.forEach(q => {
    const answers = rows
      .map(r => ({ text: (r[q.key] as string | null) || '', date: r.submitted_at, nps: r.q1_nps }))
      .filter(a => a.text && a.text.trim().length > 0)

    out.push(new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 120 },
      keepNext: true,
      children: [
        new TextRun({ text: q.label, bold: true, color: COLORS.tealDark, size: 24 }),
        new TextRun({ text: `   (${answers.length})`, italics: true, color: COLORS.inkSoft, size: 18 }),
      ],
    }))

    if (answers.length === 0) {
      out.push(p(t.openNoneFor(q.label), { italics: true, color: COLORS.inkSoft, size: 20 }))
      return
    }

    answers.forEach(a => {
      out.push(new Paragraph({
        spacing: { after: 40 },
        keepLines: true,
        children: [new TextRun({ text: a.text, size: 22 })],
      }))
      out.push(new Paragraph({
        spacing: { after: 160 },
        children: [new TextRun({
          text: `${fmtDateTime(a.date, lang)} · NPS ${a.nps}`,
          italics: true, color: COLORS.inkSoft, size: 16,
        })],
      }))
    })
  })

  return out
}

function buildRawDataSection(rows: ResponseRow[], lang: Lang, t: ReturnType<typeof L>): (Paragraph | Table)[] {
  const headers = [
    t.rawDate, t.rawNps, t.rawConcerts, t.rawAtmosphere, t.rawAcoustics, t.rawRepertoire,
    t.rawJos, t.rawComms, t.rawContribution, t.rawName,
  ]

  const headerRow = new TableRow({
    tableHeader: true,
    cantSplit: true,
    children: headers.map(h =>
      new TableCell({
        shading: { type: ShadingType.CLEAR, color: 'auto', fill: COLORS.paper },
        borders: LIGHT_BORDER,
        margins: { top: 80, bottom: 80, left: 100, right: 100 },
        children: [p(h, { bold: true, size: 16 })],
      })
    ),
  })

  const dataRows = rows.map(r =>
    new TableRow({
      cantSplit: true,
      children: [
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(fmtDateTime(r.submitted_at, lang), { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(`${r.q1_nps}`, { bold: true, size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(r.q3_aantal || '—', { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(`${r.q4_sfeer}`, { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(`${r.q6_akoestiek}`, { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(`${r.q8_repertoire}`, { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(`${r.q10_interactie}`, { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(`${r.q12_communic}`, { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(`${r.q14_bijdrage}`, { size: 16 })] }),
        new TableCell({ borders: LIGHT_BORDER, margins: { top: 60, bottom: 60, left: 100, right: 80 },
          children: [p(r.q19_naam || '—', { size: 16 })] }),
      ],
    })
  )

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
      children: [new TextRun({ text: t.rawTitle, bold: true, color: COLORS.tealDark, size: 36 })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      borders: NO_BORDER,
      rows: [headerRow, ...dataRows],
    }),
  ]
}

// ===== Main entry =====
export async function buildSurveyDocx(
  rows: ResponseRow[],
  analysis: AnalysisResult | null,
  lang: Lang,
  survey?: Survey,
): Promise<Uint8Array> {
  const t = L(lang)

  const sections = [
    // Section 1: cover (landscape, no header/footer)
    {
      properties: {
        page: {
          size: { orientation: PageOrientation.LANDSCAPE },
          margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 }, // 1 inch
        },
      },
      children: buildCover(rows, lang, t, survey),
    },
    // Section 2: rest of the report (landscape with header/footer + page numbers)
    {
      properties: {
        page: {
          size: { orientation: PageOrientation.LANDSCAPE },
          margin: { top: 1080, bottom: 1080, left: 1080, right: 1080 }, // 0.75 inch
        },
      },
      headers: {
        default: new Header({
          children: [
            new Paragraph({
              alignment: AlignmentType.RIGHT,
              children: [new TextRun({ text: t.footer, italics: true, color: COLORS.inkSoft, size: 16 })],
            }),
          ],
        }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: `${t.page} `, italics: true, color: COLORS.inkSoft, size: 16 }),
                new TextRun({ children: [PageNumber.CURRENT], italics: true, color: COLORS.inkSoft, size: 16 }),
                new TextRun({ text: ` ${t.of} `, italics: true, color: COLORS.inkSoft, size: 16 }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], italics: true, color: COLORS.inkSoft, size: 16 }),
              ],
            }),
          ],
        }),
      },
      children: [
        ...buildKpiSection(rows, lang, t),
        ...buildScoresTable(rows, lang, t),
        ...buildNpsSection(rows, lang, t),
        ...buildAttendanceSection(rows, lang, t),
        ...buildAiSection(analysis, lang, t),
        ...buildOpenAnswersSection(rows, lang, t),
        ...buildRawDataSection(rows, lang, t),
      ],
    },
  ]

  const doc = new Document({
    creator: 'Pensato.org survey dashboard',
    title: t.coverTitle,
    description: t.coverSub,
    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
        },
      },
    },
    sections,
  })

  // Packer.toBuffer returns a Uint8Array in browser/edge runtimes
  const buffer = await Packer.toBuffer(doc)
  return buffer as Uint8Array
}
