-- Test response om end-to-end werking te demonstreren
INSERT OR IGNORE INTO responses (
  id, submitted_at, ip_hash, user_agent,
  q1_nps, q2_blijft_bij, q3_aantal,
  q4_sfeer, q5_sfeer_open,
  q6_akoestiek, q7_fortepiano,
  q8_repertoire, q9_favoriet,
  q10_interactie, q11_gesprek,
  q12_communic, q13_catering,
  q14_bijdrage,
  q15_wensen_2, q16_gasten, q17_terugkomen, q18_overige,
  q19_naam, q20_contact, q20_email
) VALUES (
  'seed-test-0001',
  datetime('now', '-2 days'),
  'seed_hash',
  'Mozilla/5.0 (Test)',
  9,
  'De warme klank van de fortepiano bij kaarslicht — onvergetelijk.',
  'alle 6',
  5,
  'De huiskamer-setting maakte het persoonlijk. Geen podium, geen afstand, alleen de muziek.',
  4,
  'De fortepiano klinkt veel intiemer dan ik verwachtte — geen krachtpatser maar een fluisteraar.',
  5,
  'De Schubert-avond was een openbaring; de Fantasie in f raakte iets diep.',
  5,
  'Voldoende ruimte. Misschien iets meer tijd voor nazit.',
  4,
  'Catering was sober en passend. Misschien wat warme thee in de winter?',
  4,
  'Vroege Beethoven-sonates. Of een Mozart-cyclus. Brahms klarinetkwintet zou een droom zijn.',
  'Een violist? Of mezzosopraan voor liederen?',
  'Een seizoenkaart met 10% korting zou me direct overtuigen.',
  'Bedankt voor het initiatief — dit verdient continuïteit.',
  'Test Gebruiker',
  'ja',
  'test@example.com'
);
